[package]
name = "arc164"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
arc164-a = { alias = "a", problem = "https://atcoder.jp/contests/arc164/tasks/arc164_a" }
arc164-b = { alias = "b", problem = "https://atcoder.jp/contests/arc164/tasks/arc164_b" }
arc164-c = { alias = "c", problem = "https://atcoder.jp/contests/arc164/tasks/arc164_c" }
arc164-d = { alias = "d", problem = "https://atcoder.jp/contests/arc164/tasks/arc164_d" }
arc164-e = { alias = "e", problem = "https://atcoder.jp/contests/arc164/tasks/arc164_e" }
arc164-f = { alias = "f", problem = "https://atcoder.jp/contests/arc164/tasks/arc164_f" }

[[bin]]
name = "arc164-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc164-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc164-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc164-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc164-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc164-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
