[package]
name = "abc023"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc023-a", problem = "https://atcoder.jp/contests/abc023/<FIXME: screen name of the problem>"}
"a 2" = { name = "abc023-a 2", problem = "https://atcoder.jp/contests/abc023/<FIXME: screen name of the problem>"}
b = { name = "abc023-b", problem = "https://atcoder.jp/contests/abc023/<FIXME: screen name of the problem>"}
c = { name = "abc023-c", problem = "https://atcoder.jp/contests/abc023/<FIXME: screen name of the problem>"}
d = { name = "abc023-d", problem = "https://atcoder.jp/contests/abc023/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "abc023-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc023-a 2"
path = "./src/bin/a 2.rs"

[[bin]]
name = "abc023-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc023-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc023-d"
path = "./src/bin/d.rs"
