[package]
name = "abc201"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc201-a", problem = "https://atcoder.jp/contests/abc201/<FIXME: screen name of the problem>"}
b = { name = "abc201-b", problem = "https://atcoder.jp/contests/abc201/<FIXME: screen name of the problem>"}
c = { name = "abc201-c", problem = "https://atcoder.jp/contests/abc201/<FIXME: screen name of the problem>"}
d = { name = "abc201-d", problem = "https://atcoder.jp/contests/abc201/<FIXME: screen name of the problem>"}
e = { name = "abc201-e", problem = "https://atcoder.jp/contests/abc201/<FIXME: screen name of the problem>"}
f = { name = "abc201-f", problem = "https://atcoder.jp/contests/abc201/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "abc201-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc201-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc201-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc201-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc201-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc201-f"
path = "./src/bin/f.rs"
