[package]
name = "abc269"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc269-a", problem = "https://atcoder.jp/contests/abc269/<FIXME: screen name of the problem>"}
b = { name = "abc269-b", problem = "https://atcoder.jp/contests/abc269/<FIXME: screen name of the problem>"}
c = { name = "abc269-c", problem = "https://atcoder.jp/contests/abc269/<FIXME: screen name of the problem>"}
d = { name = "abc269-d", problem = "https://atcoder.jp/contests/abc269/<FIXME: screen name of the problem>"}
e = { name = "abc269-e", problem = "https://atcoder.jp/contests/abc269/<FIXME: screen name of the problem>"}
ex = { name = "abc269-ex", problem = "https://atcoder.jp/contests/abc269/<FIXME: screen name of the problem>"}
f = { name = "abc269-f", problem = "https://atcoder.jp/contests/abc269/<FIXME: screen name of the problem>"}
g = { name = "abc269-g", problem = "https://atcoder.jp/contests/abc269/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "abc269-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc269-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc269-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc269-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc269-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc269-ex"
path = "./src/bin/ex.rs"

[[bin]]
name = "abc269-f"
path = "./src/bin/f.rs"

[[bin]]
name = "abc269-g"
path = "./src/bin/g.rs"
