[package]
edition = "2018"
name    = "abc210"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc210-a = { alias = "a", problem = "https://atcoder.jp/contests/abc210/tasks/abc210_a" }
abc210-b = { alias = "b", problem = "https://atcoder.jp/contests/abc210/tasks/abc210_b" }
abc210-c = { alias = "c", problem = "https://atcoder.jp/contests/abc210/tasks/abc210_c" }
abc210-d = { alias = "d", problem = "https://atcoder.jp/contests/abc210/tasks/abc210_d" }
abc210-e = { alias = "e", problem = "https://atcoder.jp/contests/abc210/tasks/abc210_e" }
abc210-f = { alias = "f", problem = "https://atcoder.jp/contests/abc210/tasks/abc210_f" }

[[bin]]
name = "abc210-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc210-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc210-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc210-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc210-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc210-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
