[package]
edition = "2021"
name    = "zone2021"
version = "0.1.0"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "zone2021-a", problem = "https://atcoder.jp/contests/zone2021/<FIXME: screen name of the problem>" }
b = { name = "zone2021-b", problem = "https://atcoder.jp/contests/zone2021/<FIXME: screen name of the problem>" }
c = { name = "zone2021-c", problem = "https://atcoder.jp/contests/zone2021/<FIXME: screen name of the problem>" }
d = { name = "zone2021-d", problem = "https://atcoder.jp/contests/zone2021/<FIXME: screen name of the problem>" }
e = { name = "zone2021-e", problem = "https://atcoder.jp/contests/zone2021/<FIXME: screen name of the problem>" }
f = { name = "zone2021-f", problem = "https://atcoder.jp/contests/zone2021/<FIXME: screen name of the problem>" }

# dependencies added to new project
[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[profile.release]
lto   = true
panic = 'abort'

[[bin]]
name = "zone2021-a"
path = "./src/bin/a.rs"

[[bin]]
name = "zone2021-b"
path = "./src/bin/b.rs"

[[bin]]
name = "zone2021-c"
path = "./src/bin/c.rs"

[[bin]]
name = "zone2021-d"
path = "./src/bin/d.rs"

[[bin]]
name = "zone2021-e"
path = "./src/bin/e.rs"

[[bin]]
name = "zone2021-f"
path = "./src/bin/f.rs"
