[package]
name = "abc150"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc150-a = { alias = "a", problem = "https://atcoder.jp/contests/abc150/tasks/abc150_a" }
abc150-b = { alias = "b", problem = "https://atcoder.jp/contests/abc150/tasks/abc150_b" }
abc150-c = { alias = "c", problem = "https://atcoder.jp/contests/abc150/tasks/abc150_c" }
abc150-d = { alias = "d", problem = "https://atcoder.jp/contests/abc150/tasks/abc150_d" }
abc150-e = { alias = "e", problem = "https://atcoder.jp/contests/abc150/tasks/abc150_e" }
abc150-f = { alias = "f", problem = "https://atcoder.jp/contests/abc150/tasks/abc150_f" }

[[bin]]
name = "abc150-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc150-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc150-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc150-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc150-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc150-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
