[package]
name = "abc199"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc199-a = { alias = "a", problem = "https://atcoder.jp/contests/abc199/tasks/abc199_a" }
abc199-b = { alias = "b", problem = "https://atcoder.jp/contests/abc199/tasks/abc199_b" }
abc199-c = { alias = "c", problem = "https://atcoder.jp/contests/abc199/tasks/abc199_c" }
abc199-d = { alias = "d", problem = "https://atcoder.jp/contests/abc199/tasks/abc199_d" }
abc199-e = { alias = "e", problem = "https://atcoder.jp/contests/abc199/tasks/abc199_e" }
abc199-f = { alias = "f", problem = "https://atcoder.jp/contests/abc199/tasks/abc199_f" }

[[bin]]
name = "abc199-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc199-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc199-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc199-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc199-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc199-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
