[package]
edition = "2018"
name    = "abc412"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc412-a = { alias = "a", problem = "https://atcoder.jp/contests/abc412/tasks/abc412_a" }
abc412-b = { alias = "b", problem = "https://atcoder.jp/contests/abc412/tasks/abc412_b" }
abc412-c = { alias = "c", problem = "https://atcoder.jp/contests/abc412/tasks/abc412_c" }
abc412-d = { alias = "d", problem = "https://atcoder.jp/contests/abc412/tasks/abc412_d" }
abc412-e = { alias = "e", problem = "https://atcoder.jp/contests/abc412/tasks/abc412_e" }
abc412-f = { alias = "f", problem = "https://atcoder.jp/contests/abc412/tasks/abc412_f" }
abc412-g = { alias = "g", problem = "https://atcoder.jp/contests/abc412/tasks/abc412_g" }

[[bin]]
name = "abc412-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc412-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc412-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc412-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc412-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc412-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc412-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
