[package]
edition = "2018"
name    = "arc169"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
arc169-a = { alias = "a", problem = "https://atcoder.jp/contests/arc169/tasks/arc169_a" }
arc169-b = { alias = "b", problem = "https://atcoder.jp/contests/arc169/tasks/arc169_b" }
arc169-c = { alias = "c", problem = "https://atcoder.jp/contests/arc169/tasks/arc169_c" }
arc169-d = { alias = "d", problem = "https://atcoder.jp/contests/arc169/tasks/arc169_d" }
arc169-e = { alias = "e", problem = "https://atcoder.jp/contests/arc169/tasks/arc169_e" }
arc169-f = { alias = "f", problem = "https://atcoder.jp/contests/arc169/tasks/arc169_f" }

[[bin]]
name = "arc169-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc169-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc169-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc169-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc169-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc169-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
