workspace = {members = [
    "abc078",
    "abc129",
    "abc138",
    "abc175",
    "abc292",
    "abc298",
    "abc299",
    "abc300",
    "abc306",
    "abc308",
    "abc313",
    "abc314",
    "abc315",
    "abc317",
    "abc318",
    "abc319",
    "abc331",
    "abc332",
    "abc333",
    "abc334",
    "abc335",
    "abc336",
    "abc337",
    "abc338",
    "abc339",
    "abc340",
    "abc341",
    "abc342",
    "practice",
    "tessoku-book"
, "abc344"], exclude = []}
