[[package]]
checksum     = "8716408b8bc624ed7f65d223ddb9ac2d044c0547b6fa4b0d554f3a9540496ada"
dependencies = ["memchr"]
name         = "aho-corasick"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.7.10"

[[package]]
checksum     = "4f823d037a7ec6ea2197046bafd4ae150e6bc36f9ca347404f46a46823fa84f2"
dependencies = ["approx", "num-complex", "num-traits"]
name         = "alga"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.9.3"

[[package]]
checksum     = "f0e60b75072ecd4168020818c0107f2857bb6c4e64252d8d3983f6263b40a5c3"
dependencies = ["num-traits"]
name         = "approx"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.3.2"

[[package]]
checksum = "bbf56136a5198c7b01a49e3afcbef6cf84597273d298f54432926024107b0109"
name     = "ascii"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "1.0.0"

[[package]]
checksum = "f8aac770f1885fd7e387acedd76065302551364496e46b3dd00860b2f8359b9d"
name     = "autocfg"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "1.0.0"

[[package]]
checksum     = "031043d04099746d8db04daf1fa424b2bc8bd69d92b25962dcde24da39ab64a2"
dependencies = ["typenum"]
name         = "bitmaps"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "2.1.0"

[[package]]
checksum = "a8cc868e96ba5c32ffae4d42bf2940ca7fca317dcef3f19b6d7de66b6885abff"
name     = "bitset-fixed"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.1.0"

[[package]]
checksum = "4785bdd1c96b2a846b2bd7cc02e86b6b3dbf14e7e53446c4f54c92a361040822"
name     = "cfg-if"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.1.10"

[[package]]
checksum = "bb1f6b1ce1c140482ea30ddd3335fc0024ac7ee112895426e0a629a6c20adfe3"
name     = "either"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "1.5.3"

[[package]]
checksum = "37ab347416e802de484e4d03c7316c48f1ecb56574dfd4a46a80f173ce1de04d"
name     = "fixedbitset"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.2.0"

[[package]]
checksum     = "0ed1e761351b56f54eb9dcd0cfaca9fd0daecf93918e1cfc01c8a3d26ee7adcd"
dependencies = ["typenum"]
name         = "generic-array"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.13.2"

[[package]]
checksum     = "7abc8dd8451921606d809ba32e95b6111925cd2906060d2dcc29c070220503eb"
dependencies = ["cfg-if", "libc", "wasi"]
name         = "getrandom"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.1.14"

[[package]]
checksum = "303f7e6256d546e01979071417432425f15c1891fb309a5f2d724ee908fabd6e"
dependencies = [
    "bitmaps",
    "rand_core",
    "rand_xoshiro",
    "sized-chunks",
    "typenum",
    "version_check",
]
name = "im-rc"
source = "registry+https://github.com/rust-lang/crates.io-index"
version = "14.3.0"

[[package]]
checksum     = "076f042c5b7b98f31d205f1249267e12a6518c1481e9dae9764af19b707d2292"
dependencies = ["autocfg"]
name         = "indexmap"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "1.3.2"

[[package]]
checksum     = "f56a2d0bc861f9165be4eb3442afd3c236d8a98afd426f65d92324ae1091a484"
dependencies = ["either"]
name         = "itertools"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.8.2"

[[package]]
checksum     = "284f18f85651fe11e8a991b2adb42cb078325c996ed026d994719efcfca1d54b"
dependencies = ["either"]
name         = "itertools"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.9.0"

[[package]]
checksum     = "a872a22f9e6f7521ca557660adb96dd830e54f0f490fa115bb55dd69d38b27e7"
dependencies = ["num-traits"]
name         = "itertools-num"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.1.3"

[[package]]
checksum = "e2abad23fbc42b3700f2f279844dc832adb2b2eb069b2df918f455c4e18cc646"
name     = "lazy_static"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "1.4.0"

[[package]]
checksum = "dea0c0405123bba743ee3f91f49b1c7cfb684eef0da0a50110f758ccf24cdff0"
name     = "libc"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.2.68"

[[package]]
checksum = "c7d73b3f436185384286bd8098d17ec07c9a7d2388a6599f824d8502b529702a"
name     = "libm"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.2.1"

[[package]]
checksum = "3e2e65a1a2e43cfcb47a895c4c8b10d1f4a61097f9f254f183aee60cad9c651d"
name     = "maplit"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "1.0.2"

[[package]]
checksum     = "d4f7ec66360130972f34830bfad9ef05c6610a43938a467bcc9ab9369ab3478f"
dependencies = ["rawpointer"]
name         = "matrixmultiply"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.2.3"

[[package]]
checksum = "3728d817d99e5ac407411fa471ff9800a778d88a24685968b36824eaf4bee400"
name     = "memchr"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "2.3.3"

[[package]]
checksum = "c6511777ed3da44b6a11e732a66a7d6274dfbbcd68ad968e64b778dcb829d94a"
dependencies = [
    "alga",
    "approx",
    "generic-array",
    "matrixmultiply",
    "num-complex",
    "num-rational",
    "num-traits",
    "rand",
    "rand_distr",
    "typenum",
]
name = "nalgebra"
source = "registry+https://github.com/rust-lang/crates.io-index"
version = "0.20.0"

[[package]]
checksum = "25b001fc2f5df269365fb77bd8396ce6b1f61c9848f7f088c25e57494bacc57b"
dependencies = [
    "itertools 0.8.2",
    "matrixmultiply",
    "num-complex",
    "num-integer",
    "num-traits",
    "rawpointer",
]
name = "ndarray"
source = "registry+https://github.com/rust-lang/crates.io-index"
version = "0.13.0"

[[package]]
checksum = "b8536030f9fea7127f841b45bb6243b27255787fb4eb83958aa1ef9d2fdc0c36"
dependencies = [
    "num-bigint",
    "num-complex",
    "num-integer",
    "num-iter",
    "num-rational",
    "num-traits",
]
name = "num"
source = "registry+https://github.com/rust-lang/crates.io-index"
version = "0.2.1"

[[package]]
checksum     = "090c7f9998ee0ff65aa5b723e4009f7b217707f1fb5ea551329cc4d6231fb304"
dependencies = ["autocfg", "num-integer", "num-traits"]
name         = "num-bigint"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.2.6"

[[package]]
checksum     = "b6b19411a9719e753aff12e5187b74d60d3dc449ec3f4dc21e3989c3f554bc95"
dependencies = ["autocfg", "num-traits"]
name         = "num-complex"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.2.4"

[[package]]
checksum     = "0c8b15b261814f992e33760b1fca9fe8b693d8a65299f20c9901688636cfb746"
dependencies = ["proc-macro2 1.0.10", "quote 1.0.3", "syn 1.0.17"]
name         = "num-derive"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.3.0"

[[package]]
checksum     = "3f6ea62e9d81a77cd3ee9a2a5b9b609447857f3d358704331e4ef39eb247fcba"
dependencies = ["autocfg", "num-traits"]
name         = "num-integer"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.1.42"

[[package]]
checksum     = "dfb0800a0291891dd9f4fe7bd9c19384f98f7fbe0cd0f39a2c6b88b9868bbc00"
dependencies = ["autocfg", "num-integer", "num-traits"]
name         = "num-iter"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.1.40"

[[package]]
checksum     = "5c000134b5dbf44adc5cb772486d335293351644b801551abe8f75c84cfa4aef"
dependencies = ["autocfg", "num-bigint", "num-integer", "num-traits"]
name         = "num-rational"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.2.4"

[[package]]
checksum     = "c62be47e61d1842b9170f0fdeec8eba98e60e90e5446449a0545e5152acd7096"
dependencies = ["autocfg", "libm"]
name         = "num-traits"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.2.11"

[[package]]
checksum     = "18869315e81473c951eb56ad5558bbc56978562d3ecfb87abb7a1e944cea4518"
dependencies = ["num-traits"]
name         = "ordered-float"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "1.0.2"

[[package]]
checksum = "b687ff7b5da449d39e418ad391e5e08da53ec334903ddbb921db208908fc372c"
name     = "permutohedron"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.2.4"

[[package]]
checksum     = "29c127eea4a29ec6c85d153c59dc1213f33ec74cead30fe4730aecc88cc1fd92"
dependencies = ["fixedbitset", "indexmap"]
name         = "petgraph"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.5.0"

[[package]]
checksum = "74490b50b9fbe561ac330df47c08f3f33073d2d00c150f719147d7c54522fa1b"
name     = "ppv-lite86"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.2.6"

[[package]]
checksum     = "cf3d2011ab5c909338f7887f4fc896d35932e29146c12c8d01da6b22a80ba759"
dependencies = ["unicode-xid 0.1.0"]
name         = "proc-macro2"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.4.30"

[[package]]
checksum     = "df246d292ff63439fea9bc8c0a270bed0e390d5ebd4db4ba15aba81111b5abe3"
dependencies = ["unicode-xid 0.2.0"]
name         = "proc-macro2"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "1.0.10"

[[package]]
checksum     = "3bed4f95f88d84bb8efd51dbc080d463e6ca953f05dfade2e24daf19dd861ccd"
dependencies = ["lazy_static", "proconio-derive"]
name         = "proconio"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.3.6"

[[package]]
checksum     = "fc2f2111a9562adf5ba291143c434818c908a05636c8a492a0a69ba4720a2c16"
dependencies = ["proc-macro2 0.4.30", "quote 0.6.13", "syn 0.15.44"]
name         = "proconio-derive"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.1.6"

[[package]]
checksum     = "6ce23b6b870e8f94f81fb0a363d65d86675884b34a09043c81e5562f11c1f8e1"
dependencies = ["proc-macro2 0.4.30"]
name         = "quote"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.6.13"

[[package]]
checksum     = "2bdc6c187c65bca4260c9011c9e3132efe4909da44726bad24cf7572ae338d7f"
dependencies = ["proc-macro2 1.0.10"]
name         = "quote"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "1.0.3"

[[package]]
checksum = "6a6b1679d49b24bbfe0c803429aa1874472f50d9b363131f0e89fc356b544d03"
dependencies = [
    "getrandom",
    "libc",
    "rand_chacha",
    "rand_core",
    "rand_hc",
    "rand_pcg",
]
name = "rand"
source = "registry+https://github.com/rust-lang/crates.io-index"
version = "0.7.3"

[[package]]
checksum     = "f4c8ed856279c9737206bf725bf36935d8666ead7aa69b52be55af369d193402"
dependencies = ["ppv-lite86", "rand_core"]
name         = "rand_chacha"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.2.2"

[[package]]
checksum     = "90bde5296fc891b0cef12a6d03ddccc162ce7b2aff54160af9338f8d40df6d19"
dependencies = ["getrandom"]
name         = "rand_core"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.5.1"

[[package]]
checksum     = "96977acbdd3a6576fb1d27391900035bf3863d4a16422973a409b488cf29ffb2"
dependencies = ["rand"]
name         = "rand_distr"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.2.2"

[[package]]
checksum     = "ca3129af7b92a17112d59ad498c6f81eaf463253766b90396d39ea7a39d6613c"
dependencies = ["rand_core"]
name         = "rand_hc"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.2.0"

[[package]]
checksum     = "16abd0c1b639e9eb4d7c50c0b8100b0d0f849be2349829c740fe8e6eb4816429"
dependencies = ["rand_core"]
name         = "rand_pcg"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.2.1"

[[package]]
checksum     = "a9fcdd2e881d02f1d9390ae47ad8e5696a9e4be7b547a1da2afbc61973217004"
dependencies = ["rand_core"]
name         = "rand_xoshiro"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.4.0"

[[package]]
checksum = "60a357793950651c4ed0f3f52338f53b2f809f32d83a07f72909fa13e4c6c1e3"
name     = "rawpointer"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.2.1"

[[package]]
checksum     = "7f6946991529684867e47d86474e3a6d0c0ab9b82d5821e314b1ede31fa3a4b3"
dependencies = ["aho-corasick", "memchr", "regex-syntax", "thread_local"]
name         = "regex"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "1.3.6"

[[package]]
checksum = "7fe5bd57d1d7414c6b5ed48563a2c855d995ff777729dcd91c369ec7fea395ae"
name     = "regex-syntax"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.6.17"

[[package]]
checksum = "08d43f7aa6b08d49f382cde6a7982047c3426db949b1424bc4b7ec9ae12c6ce2"
name     = "rustc-hash"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "1.1.0"

[[package]]
checksum     = "d59044ea371ad781ff976f7b06480b9f0180e834eda94114f2afb4afc12b7718"
dependencies = ["bitmaps", "typenum"]
name         = "sized-chunks"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.5.3"

[[package]]
checksum = "5c2fb2ec9bcd216a5b0d0ccf31ab17b5ed1d627960edff65bbe95d3ce221cefc"
name     = "smallvec"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "1.2.0"

[[package]]
checksum = "ab16ced94dbd8a46c82fd81e3ed9a8727dac2977ea869d217bcc4ea1f122e81f"
name     = "superslice"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "1.0.0"

[[package]]
checksum     = "9ca4b3b69a77cbe1ffc9e198781b7acb0c7365a883670e8f1c1bc66fba79a5c5"
dependencies = ["proc-macro2 0.4.30", "quote 0.6.13", "unicode-xid 0.1.0"]
name         = "syn"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "0.15.44"

[[package]]
checksum     = "0df0eb663f387145cab623dea85b09c2c5b4b0aef44e945d928e682fce71bb03"
dependencies = ["proc-macro2 1.0.10", "quote 1.0.3", "unicode-xid 0.2.0"]
name         = "syn"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "1.0.17"

[[package]]
checksum = "6cb170b4f47dc48835fbc56259c12d8963e542b05a24be2e3a1f5a6c320fd2d4"
name     = "text_io"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.1.8"

[[package]]
checksum     = "d40c6d1b69745a6ec6fb1ca717914848da4b44ae29d9b3080cbee91d72a69b14"
dependencies = ["lazy_static"]
name         = "thread_local"
source       = "registry+https://github.com/rust-lang/crates.io-index"
version      = "1.0.1"

[[package]]
checksum = "6d2783fe2d6b8c1101136184eb41be8b1ad379e4657050b8aaff0c79ee7575f9"
name     = "typenum"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "1.11.2"

[[package]]
checksum = "fc72304796d0818e357ead4e000d19c9c174ab23dc11093ac919054d20a6a7fc"
name     = "unicode-xid"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.1.0"

[[package]]
checksum = "826e7639553986605ec5979c7dd957c7895e93eabed50ab2ffa7f6128a75097c"
name     = "unicode-xid"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.2.0"

[[package]]
checksum = "078775d0255232fb988e6fccf26ddc9d1ac274299aaedcedce21c6f72cc533ce"
name     = "version_check"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.9.1"

[[package]]
checksum = "cccddf32554fecc6acb585f82a32a72e28b48f8c4c1883ddfeeeaa96f7d8e519"
name     = "wasi"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.9.0+wasi-snapshot-preview1"

[[package]]
checksum = "8bc25de0a968755322a6b517a7257df7ec3216ed7907b8fc064906542f9714b3"
name     = "whiteread"
source   = "registry+https://github.com/rust-lang/crates.io-index"
version  = "0.5.0"
