[package]
name = "arc168"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
arc168-a = { alias = "a", problem = "https://atcoder.jp/contests/arc168/tasks/arc168_a" }
arc168-b = { alias = "b", problem = "https://atcoder.jp/contests/arc168/tasks/arc168_b" }
arc168-c = { alias = "c", problem = "https://atcoder.jp/contests/arc168/tasks/arc168_c" }
arc168-d = { alias = "d", problem = "https://atcoder.jp/contests/arc168/tasks/arc168_d" }
arc168-e = { alias = "e", problem = "https://atcoder.jp/contests/arc168/tasks/arc168_e" }
arc168-f = { alias = "f", problem = "https://atcoder.jp/contests/arc168/tasks/arc168_f" }

[[bin]]
name = "arc168-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc168-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc168-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc168-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc168-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc168-f"
path = "src/bin/f.rs"

[dependencies]
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
