[package]
edition = "2018"
name    = "abc417"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc417-a = { alias = "a", problem = "https://atcoder.jp/contests/abc417/tasks/abc417_a" }
abc417-b = { alias = "b", problem = "https://atcoder.jp/contests/abc417/tasks/abc417_b" }
abc417-c = { alias = "c", problem = "https://atcoder.jp/contests/abc417/tasks/abc417_c" }
abc417-d = { alias = "d", problem = "https://atcoder.jp/contests/abc417/tasks/abc417_d" }
abc417-e = { alias = "e", problem = "https://atcoder.jp/contests/abc417/tasks/abc417_e" }
abc417-f = { alias = "f", problem = "https://atcoder.jp/contests/abc417/tasks/abc417_f" }
abc417-g = { alias = "g", problem = "https://atcoder.jp/contests/abc417/tasks/abc417_g" }

[[bin]]
name = "abc417-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc417-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc417-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc417-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc417-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc417-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc417-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
