[package]
name = "abc299"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc299-a", problem = "https://atcoder.jp/contests/abc299/<FIXME: screen name of the problem>"}
b = { name = "abc299-b", problem = "https://atcoder.jp/contests/abc299/<FIXME: screen name of the problem>"}
c = { name = "abc299-c", problem = "https://atcoder.jp/contests/abc299/<FIXME: screen name of the problem>"}
d = { name = "abc299-d", problem = "https://atcoder.jp/contests/abc299/<FIXME: screen name of the problem>"}
e = { name = "abc299-e", problem = "https://atcoder.jp/contests/abc299/<FIXME: screen name of the problem>"}
ex = { name = "abc299-ex", problem = "https://atcoder.jp/contests/abc299/<FIXME: screen name of the problem>"}
f = { name = "abc299-f", problem = "https://atcoder.jp/contests/abc299/<FIXME: screen name of the problem>"}
g = { name = "abc299-g", problem = "https://atcoder.jp/contests/abc299/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "abc299-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc299-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc299-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc299-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc299-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc299-ex"
path = "./src/bin/ex.rs"

[[bin]]
name = "abc299-f"
path = "./src/bin/f.rs"

[[bin]]
name = "abc299-g"
path = "./src/bin/g.rs"
