[package]
name = "arc026"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "arc026-a", problem = "https://atcoder.jp/contests/arc026/<FIXME: screen name of the problem>"}
b = { name = "arc026-b", problem = "https://atcoder.jp/contests/arc026/<FIXME: screen name of the problem>"}
c = { name = "arc026-c", problem = "https://atcoder.jp/contests/arc026/<FIXME: screen name of the problem>"}
d = { name = "arc026-d", problem = "https://atcoder.jp/contests/arc026/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "arc026-a"
path = "./src/bin/a.rs"

[[bin]]
name = "arc026-b"
path = "./src/bin/b.rs"

[[bin]]
name = "arc026-c"
path = "./src/bin/c.rs"

[[bin]]
name = "arc026-d"
path = "./src/bin/d.rs"
