[package]
name = "arc151"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
arc151-a = { alias = "a", problem = "https://atcoder.jp/contests/arc151/tasks/arc151_a" }
arc151-b = { alias = "b", problem = "https://atcoder.jp/contests/arc151/tasks/arc151_b" }
arc151-c = { alias = "c", problem = "https://atcoder.jp/contests/arc151/tasks/arc151_c" }
arc151-d = { alias = "d", problem = "https://atcoder.jp/contests/arc151/tasks/arc151_d" }
arc151-e = { alias = "e", problem = "https://atcoder.jp/contests/arc151/tasks/arc151_e" }
arc151-f = { alias = "f", problem = "https://atcoder.jp/contests/arc151/tasks/arc151_f" }

[[bin]]
name = "arc151-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc151-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc151-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc151-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc151-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc151-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
