[package]
edition = "2018"
name    = "abc416"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc416-a = { alias = "a", problem = "https://atcoder.jp/contests/abc416/tasks/abc416_a" }
abc416-b = { alias = "b", problem = "https://atcoder.jp/contests/abc416/tasks/abc416_b" }
abc416-c = { alias = "c", problem = "https://atcoder.jp/contests/abc416/tasks/abc416_c" }
abc416-d = { alias = "d", problem = "https://atcoder.jp/contests/abc416/tasks/abc416_d" }
abc416-e = { alias = "e", problem = "https://atcoder.jp/contests/abc416/tasks/abc416_e" }
abc416-f = { alias = "f", problem = "https://atcoder.jp/contests/abc416/tasks/abc416_f" }
abc416-g = { alias = "g", problem = "https://atcoder.jp/contests/abc416/tasks/abc416_g" }

[[bin]]
name = "abc416-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc416-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc416-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc416-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc416-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc416-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc416-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
