[package]
name = "abc405"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc405-a = { alias = "a", problem = "https://atcoder.jp/contests/abc405/tasks/abc405_a" }
abc405-b = { alias = "b", problem = "https://atcoder.jp/contests/abc405/tasks/abc405_b" }
abc405-c = { alias = "c", problem = "https://atcoder.jp/contests/abc405/tasks/abc405_c" }
abc405-d = { alias = "d", problem = "https://atcoder.jp/contests/abc405/tasks/abc405_d" }
abc405-e = { alias = "e", problem = "https://atcoder.jp/contests/abc405/tasks/abc405_e" }
abc405-f = { alias = "f", problem = "https://atcoder.jp/contests/abc405/tasks/abc405_f" }
abc405-g = { alias = "g", problem = "https://atcoder.jp/contests/abc405/tasks/abc405_g" }

[[bin]]
name = "abc405-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc405-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc405-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc405-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc405-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc405-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc405-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
