[package]
name = "abc360"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc360-a = { alias = "a", problem = "https://atcoder.jp/contests/abc360/tasks/abc360_a" }
abc360-b = { alias = "b", problem = "https://atcoder.jp/contests/abc360/tasks/abc360_b" }
abc360-c = { alias = "c", problem = "https://atcoder.jp/contests/abc360/tasks/abc360_c" }
abc360-d = { alias = "d", problem = "https://atcoder.jp/contests/abc360/tasks/abc360_d" }
abc360-e = { alias = "e", problem = "https://atcoder.jp/contests/abc360/tasks/abc360_e" }
abc360-f = { alias = "f", problem = "https://atcoder.jp/contests/abc360/tasks/abc360_f" }
abc360-g = { alias = "g", problem = "https://atcoder.jp/contests/abc360/tasks/abc360_g" }

[[bin]]
name = "abc360-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc360-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc360-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc360-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc360-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc360-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc360-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
