[package]
name = "abc315"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc315-a = { alias = "a", problem = "https://atcoder.jp/contests/abc315/tasks/abc315_a" }
abc315-b = { alias = "b", problem = "https://atcoder.jp/contests/abc315/tasks/abc315_b" }
abc315-c = { alias = "c", problem = "https://atcoder.jp/contests/abc315/tasks/abc315_c" }
abc315-d = { alias = "d", problem = "https://atcoder.jp/contests/abc315/tasks/abc315_d" }
abc315-e = { alias = "e", problem = "https://atcoder.jp/contests/abc315/tasks/abc315_e" }
abc315-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc315/tasks/abc315_h" }
abc315-f = { alias = "f", problem = "https://atcoder.jp/contests/abc315/tasks/abc315_f" }
abc315-g = { alias = "g", problem = "https://atcoder.jp/contests/abc315/tasks/abc315_g" }

[[bin]]
name = "abc315-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc315-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc315-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc315-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc315-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc315-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc315-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc315-g"
path = "src/bin/g.rs"

[dependencies]
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
