[package]
edition = "2018"
name    = "abc356"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc356-a = { alias = "a", problem = "https://atcoder.jp/contests/abc356/tasks/abc356_a" }
abc356-b = { alias = "b", problem = "https://atcoder.jp/contests/abc356/tasks/abc356_b" }
abc356-c = { alias = "c", problem = "https://atcoder.jp/contests/abc356/tasks/abc356_c" }
abc356-d = { alias = "d", problem = "https://atcoder.jp/contests/abc356/tasks/abc356_d" }
abc356-e = { alias = "e", problem = "https://atcoder.jp/contests/abc356/tasks/abc356_e" }
abc356-f = { alias = "f", problem = "https://atcoder.jp/contests/abc356/tasks/abc356_f" }
abc356-g = { alias = "g", problem = "https://atcoder.jp/contests/abc356/tasks/abc356_g" }

[[bin]]
name = "abc356-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc356-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc356-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc356-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc356-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc356-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc356-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
