[package]
edition = "2018"
name    = "agc019"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
agc019-a = { alias = "a", problem = "https://atcoder.jp/contests/agc019/tasks/agc019_a" }
agc019-b = { alias = "b", problem = "https://atcoder.jp/contests/agc019/tasks/agc019_b" }
agc019-c = { alias = "c", problem = "https://atcoder.jp/contests/agc019/tasks/agc019_c" }
agc019-d = { alias = "d", problem = "https://atcoder.jp/contests/agc019/tasks/agc019_d" }
agc019-e = { alias = "e", problem = "https://atcoder.jp/contests/agc019/tasks/agc019_e" }
agc019-f = { alias = "f", problem = "https://atcoder.jp/contests/agc019/tasks/agc019_f" }

[[bin]]
name = "agc019-a"
path = "src/bin/a.rs"

[[bin]]
name = "agc019-b"
path = "src/bin/b.rs"

[[bin]]
name = "agc019-c"
path = "src/bin/c.rs"

[[bin]]
name = "agc019-d"
path = "src/bin/d.rs"

[[bin]]
name = "agc019-e"
path = "src/bin/e.rs"

[[bin]]
name = "agc019-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
