[package]
name = "abc190"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc190-a = { alias = "a", problem = "https://atcoder.jp/contests/abc190/tasks/abc190_a" }
abc190-b = { alias = "b", problem = "https://atcoder.jp/contests/abc190/tasks/abc190_b" }
abc190-c = { alias = "c", problem = "https://atcoder.jp/contests/abc190/tasks/abc190_c" }
abc190-d = { alias = "d", problem = "https://atcoder.jp/contests/abc190/tasks/abc190_d" }
abc190-e = { alias = "e", problem = "https://atcoder.jp/contests/abc190/tasks/abc190_e" }
abc190-f = { alias = "f", problem = "https://atcoder.jp/contests/abc190/tasks/abc190_f" }

[[bin]]
name = "abc190-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc190-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc190-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc190-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc190-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc190-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
