[package]
edition = "2018"
name    = "arc179"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
arc179-a = { alias = "a", problem = "https://atcoder.jp/contests/arc179/tasks/arc179_a" }
arc179-b = { alias = "b", problem = "https://atcoder.jp/contests/arc179/tasks/arc179_b" }
arc179-c = { alias = "c", problem = "https://atcoder.jp/contests/arc179/tasks/arc179_c" }
arc179-d = { alias = "d", problem = "https://atcoder.jp/contests/arc179/tasks/arc179_d" }
arc179-e = { alias = "e", problem = "https://atcoder.jp/contests/arc179/tasks/arc179_e" }
arc179-f = { alias = "f", problem = "https://atcoder.jp/contests/arc179/tasks/arc179_f" }

[[bin]]
name = "arc179-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc179-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc179-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc179-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc179-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc179-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
