[package]
edition = "2018"
name    = "abc158"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc158-a = { alias = "a", problem = "https://atcoder.jp/contests/abc158/tasks/abc158_a" }
abc158-b = { alias = "b", problem = "https://atcoder.jp/contests/abc158/tasks/abc158_b" }
abc158-c = { alias = "c", problem = "https://atcoder.jp/contests/abc158/tasks/abc158_c" }
abc158-d = { alias = "d", problem = "https://atcoder.jp/contests/abc158/tasks/abc158_d" }
abc158-e = { alias = "e", problem = "https://atcoder.jp/contests/abc158/tasks/abc158_e" }
abc158-f = { alias = "f", problem = "https://atcoder.jp/contests/abc158/tasks/abc158_f" }

[[bin]]
name = "abc158-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc158-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc158-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc158-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc158-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc158-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
