[package]
name = "code-formula-2014-qualb"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "code-formula-2014-qualb-a", problem = "https://atcoder.jp/contests/code-formula-2014-qualb/<FIXME: screen name of the problem>"}
b = { name = "code-formula-2014-qualb-b", problem = "https://atcoder.jp/contests/code-formula-2014-qualb/<FIXME: screen name of the problem>"}
c = { name = "code-formula-2014-qualb-c", problem = "https://atcoder.jp/contests/code-formula-2014-qualb/<FIXME: screen name of the problem>"}
d = { name = "code-formula-2014-qualb-d", problem = "https://atcoder.jp/contests/code-formula-2014-qualb/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "code-formula-2014-qualb-a"
path = "./src/bin/a.rs"

[[bin]]
name = "code-formula-2014-qualb-b"
path = "./src/bin/b.rs"

[[bin]]
name = "code-formula-2014-qualb-c"
path = "./src/bin/c.rs"

[[bin]]
name = "code-formula-2014-qualb-d"
path = "./src/bin/d.rs"
