[package]
name = "abc256"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc256-a = { alias = "a", problem = "https://atcoder.jp/contests/abc256/tasks/abc256_a" }
abc256-b = { alias = "b", problem = "https://atcoder.jp/contests/abc256/tasks/abc256_b" }
abc256-c = { alias = "c", problem = "https://atcoder.jp/contests/abc256/tasks/abc256_c" }
abc256-d = { alias = "d", problem = "https://atcoder.jp/contests/abc256/tasks/abc256_d" }
abc256-e = { alias = "e", problem = "https://atcoder.jp/contests/abc256/tasks/abc256_e" }
abc256-ex = { alias = "ex", problem = "https://atcoder.jp/contests/abc256/tasks/abc256_h" }
abc256-f = { alias = "f", problem = "https://atcoder.jp/contests/abc256/tasks/abc256_f" }
abc256-g = { alias = "g", problem = "https://atcoder.jp/contests/abc256/tasks/abc256_g" }

[[bin]]
name = "abc256-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc256-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc256-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc256-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc256-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc256-ex"
path = "src/bin/ex.rs"

[[bin]]
name = "abc256-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc256-g"
path = "src/bin/g.rs"

[dependencies]
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
