[package]
name = "abc305"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc305-a", problem = "https://atcoder.jp/contests/abc305/<FIXME: screen name of the problem>"}
b = { name = "abc305-b", problem = "https://atcoder.jp/contests/abc305/<FIXME: screen name of the problem>"}
c = { name = "abc305-c", problem = "https://atcoder.jp/contests/abc305/<FIXME: screen name of the problem>"}
d = { name = "abc305-d", problem = "https://atcoder.jp/contests/abc305/<FIXME: screen name of the problem>"}
e = { name = "abc305-e", problem = "https://atcoder.jp/contests/abc305/<FIXME: screen name of the problem>"}
ex = { name = "abc305-ex", problem = "https://atcoder.jp/contests/abc305/<FIXME: screen name of the problem>"}
f = { name = "abc305-f", problem = "https://atcoder.jp/contests/abc305/<FIXME: screen name of the problem>"}
g = { name = "abc305-g", problem = "https://atcoder.jp/contests/abc305/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"
itertools = "=0.9.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "abc305-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc305-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc305-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc305-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc305-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc305-ex"
path = "./src/bin/ex.rs"

[[bin]]
name = "abc305-f"
path = "./src/bin/f.rs"

[[bin]]
name = "abc305-g"
path = "./src/bin/g.rs"
