[package]
name = "arc104"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "arc104-a", problem = "https://atcoder.jp/contests/arc104/<FIXME: screen name of the problem>"}
b = { name = "arc104-b", problem = "https://atcoder.jp/contests/arc104/<FIXME: screen name of the problem>"}
c = { name = "arc104-c", problem = "https://atcoder.jp/contests/arc104/<FIXME: screen name of the problem>"}
d = { name = "arc104-d", problem = "https://atcoder.jp/contests/arc104/<FIXME: screen name of the problem>"}
e = { name = "arc104-e", problem = "https://atcoder.jp/contests/arc104/<FIXME: screen name of the problem>"}
f = { name = "arc104-f", problem = "https://atcoder.jp/contests/arc104/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "arc104-a"
path = "./src/bin/a.rs"

[[bin]]
name = "arc104-b"
path = "./src/bin/b.rs"

[[bin]]
name = "arc104-c"
path = "./src/bin/c.rs"

[[bin]]
name = "arc104-d"
path = "./src/bin/d.rs"

[[bin]]
name = "arc104-e"
path = "./src/bin/e.rs"

[[bin]]
name = "arc104-f"
path = "./src/bin/f.rs"
