[package]
name = "abc198"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc198-a = { alias = "a", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_a" }
abc198-b = { alias = "b", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_b" }
abc198-c = { alias = "c", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_c" }
abc198-d = { alias = "d", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_d" }
abc198-e = { alias = "e", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_e" }
abc198-f = { alias = "f", problem = "https://atcoder.jp/contests/abc198/tasks/abc198_f" }

[[bin]]
name = "abc198-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc198-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc198-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc198-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc198-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc198-f"
path = "src/bin/f.rs"

[dependencies]
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
