[package]
name = "abc162"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc162-a = { alias = "a", problem = "https://atcoder.jp/contests/abc162/tasks/abc162_a" }
abc162-b = { alias = "b", problem = "https://atcoder.jp/contests/abc162/tasks/abc162_b" }
abc162-c = { alias = "c", problem = "https://atcoder.jp/contests/abc162/tasks/abc162_c" }
abc162-d = { alias = "d", problem = "https://atcoder.jp/contests/abc162/tasks/abc162_d" }
abc162-e = { alias = "e", problem = "https://atcoder.jp/contests/abc162/tasks/abc162_e" }
abc162-f = { alias = "f", problem = "https://atcoder.jp/contests/abc162/tasks/abc162_f" }

[[bin]]
name = "abc162-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc162-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc162-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc162-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc162-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc162-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
