[package]
name = "abc167"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc167-a = { alias = "a", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_a" }
abc167-b = { alias = "b", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_b" }
abc167-c = { alias = "c", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_c" }
abc167-d = { alias = "d", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_d" }
abc167-e = { alias = "e", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_e" }
abc167-f = { alias = "f", problem = "https://atcoder.jp/contests/abc167/tasks/abc167_f" }

[[bin]]
name = "abc167-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc167-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc167-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc167-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc167-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc167-f"
path = "src/bin/f.rs"

[dependencies]
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
