[package]
name = "abc143"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc143-a = { alias = "a", problem = "https://atcoder.jp/contests/abc143/tasks/abc143_a" }
abc143-b = { alias = "b", problem = "https://atcoder.jp/contests/abc143/tasks/abc143_b" }
abc143-c = { alias = "c", problem = "https://atcoder.jp/contests/abc143/tasks/abc143_c" }
abc143-d = { alias = "d", problem = "https://atcoder.jp/contests/abc143/tasks/abc143_d" }
abc143-e = { alias = "e", problem = "https://atcoder.jp/contests/abc143/tasks/abc143_e" }
abc143-f = { alias = "f", problem = "https://atcoder.jp/contests/abc143/tasks/abc143_f" }

[[bin]]
name = "abc143-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc143-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc143-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc143-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc143-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc143-f"
path = "src/bin/f.rs"

[dependencies]
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
