[package]
name = "arc144"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "arc144-a", problem = "https://atcoder.jp/contests/arc144/<FIXME: screen name of the problem>"}
"a 2" = { name = "arc144-a 2", problem = "https://atcoder.jp/contests/arc144/<FIXME: screen name of the problem>"}
b = { name = "arc144-b", problem = "https://atcoder.jp/contests/arc144/<FIXME: screen name of the problem>"}
c = { name = "arc144-c", problem = "https://atcoder.jp/contests/arc144/<FIXME: screen name of the problem>"}
d = { name = "arc144-d", problem = "https://atcoder.jp/contests/arc144/<FIXME: screen name of the problem>"}
e = { name = "arc144-e", problem = "https://atcoder.jp/contests/arc144/<FIXME: screen name of the problem>"}
f = { name = "arc144-f", problem = "https://atcoder.jp/contests/arc144/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "arc144-a"
path = "./src/bin/a.rs"

[[bin]]
name = "arc144-a 2"
path = "./src/bin/a 2.rs"

[[bin]]
name = "arc144-b"
path = "./src/bin/b.rs"

[[bin]]
name = "arc144-c"
path = "./src/bin/c.rs"

[[bin]]
name = "arc144-d"
path = "./src/bin/d.rs"

[[bin]]
name = "arc144-e"
path = "./src/bin/e.rs"

[[bin]]
name = "arc144-f"
path = "./src/bin/f.rs"
