[package]
name = "abc358"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc358-a = { alias = "a", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_a" }
abc358-b = { alias = "b", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_b" }
abc358-c = { alias = "c", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_c" }
abc358-d = { alias = "d", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_d" }
abc358-e = { alias = "e", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_e" }
abc358-f = { alias = "f", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_f" }
abc358-g = { alias = "g", problem = "https://atcoder.jp/contests/abc358/tasks/abc358_g" }

[[bin]]
name = "abc358-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc358-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc358-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc358-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc358-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc358-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc358-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
