[package]
edition = "2018"
name    = "abc414"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc414-a = { alias = "a", problem = "https://atcoder.jp/contests/abc414/tasks/abc414_a" }
abc414-b = { alias = "b", problem = "https://atcoder.jp/contests/abc414/tasks/abc414_b" }
abc414-c = { alias = "c", problem = "https://atcoder.jp/contests/abc414/tasks/abc414_c" }
abc414-d = { alias = "d", problem = "https://atcoder.jp/contests/abc414/tasks/abc414_d" }
abc414-e = { alias = "e", problem = "https://atcoder.jp/contests/abc414/tasks/abc414_e" }
abc414-f = { alias = "f", problem = "https://atcoder.jp/contests/abc414/tasks/abc414_f" }
abc414-g = { alias = "g", problem = "https://atcoder.jp/contests/abc414/tasks/abc414_g" }

[[bin]]
name = "abc414-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc414-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc414-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc414-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc414-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc414-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc414-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
