[package]
name = "abc249"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc249-a", problem = "https://atcoder.jp/contests/abc249/<FIXME: screen name of the problem>"}
b = { name = "abc249-b", problem = "https://atcoder.jp/contests/abc249/<FIXME: screen name of the problem>"}
c = { name = "abc249-c", problem = "https://atcoder.jp/contests/abc249/<FIXME: screen name of the problem>"}
d = { name = "abc249-d", problem = "https://atcoder.jp/contests/abc249/<FIXME: screen name of the problem>"}
e = { name = "abc249-e", problem = "https://atcoder.jp/contests/abc249/<FIXME: screen name of the problem>"}
ex = { name = "abc249-ex", problem = "https://atcoder.jp/contests/abc249/<FIXME: screen name of the problem>"}
f = { name = "abc249-f", problem = "https://atcoder.jp/contests/abc249/<FIXME: screen name of the problem>"}
g = { name = "abc249-g", problem = "https://atcoder.jp/contests/abc249/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "abc249-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc249-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc249-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc249-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc249-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc249-ex"
path = "./src/bin/ex.rs"

[[bin]]
name = "abc249-f"
path = "./src/bin/f.rs"

[[bin]]
name = "abc249-g"
path = "./src/bin/g.rs"
