[package]
edition = "2018"
name    = "abc203"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc203-a = { alias = "a", problem = "https://atcoder.jp/contests/abc203/tasks/abc203_a" }
abc203-b = { alias = "b", problem = "https://atcoder.jp/contests/abc203/tasks/abc203_b" }
abc203-c = { alias = "c", problem = "https://atcoder.jp/contests/abc203/tasks/abc203_c" }
abc203-d = { alias = "d", problem = "https://atcoder.jp/contests/abc203/tasks/abc203_d" }
abc203-e = { alias = "e", problem = "https://atcoder.jp/contests/abc203/tasks/abc203_e" }
abc203-f = { alias = "f", problem = "https://atcoder.jp/contests/abc203/tasks/abc203_f" }

[[bin]]
name = "abc203-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc203-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc203-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc203-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc203-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc203-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
