[package]
name = "abc408"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc408-a = { alias = "a", problem = "https://atcoder.jp/contests/abc408/tasks/abc408_a" }
abc408-b = { alias = "b", problem = "https://atcoder.jp/contests/abc408/tasks/abc408_b" }
abc408-c = { alias = "c", problem = "https://atcoder.jp/contests/abc408/tasks/abc408_c" }
abc408-d = { alias = "d", problem = "https://atcoder.jp/contests/abc408/tasks/abc408_d" }
abc408-e = { alias = "e", problem = "https://atcoder.jp/contests/abc408/tasks/abc408_e" }
abc408-f = { alias = "f", problem = "https://atcoder.jp/contests/abc408/tasks/abc408_f" }
abc408-g = { alias = "g", problem = "https://atcoder.jp/contests/abc408/tasks/abc408_g" }

[[bin]]
name = "abc408-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc408-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc408-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc408-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc408-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc408-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc408-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
