[package]
name = "abc303"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc303-a", problem = "https://atcoder.jp/contests/abc303/<FIXME: screen name of the problem>"}
b = { name = "abc303-b", problem = "https://atcoder.jp/contests/abc303/<FIXME: screen name of the problem>"}
c = { name = "abc303-c", problem = "https://atcoder.jp/contests/abc303/<FIXME: screen name of the problem>"}
d = { name = "abc303-d", problem = "https://atcoder.jp/contests/abc303/<FIXME: screen name of the problem>"}
e = { name = "abc303-e", problem = "https://atcoder.jp/contests/abc303/<FIXME: screen name of the problem>"}
ex = { name = "abc303-ex", problem = "https://atcoder.jp/contests/abc303/<FIXME: screen name of the problem>"}
f = { name = "abc303-f", problem = "https://atcoder.jp/contests/abc303/<FIXME: screen name of the problem>"}
g = { name = "abc303-g", problem = "https://atcoder.jp/contests/abc303/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"
itertools = "=0.9.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "abc303-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc303-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc303-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc303-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc303-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc303-ex"
path = "./src/bin/ex.rs"

[[bin]]
name = "abc303-f"
path = "./src/bin/f.rs"

[[bin]]
name = "abc303-g"
path = "./src/bin/g.rs"
