[package]
name = "abc173"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc173-a = { alias = "a", problem = "https://atcoder.jp/contests/abc173/tasks/abc173_a" }
abc173-b = { alias = "b", problem = "https://atcoder.jp/contests/abc173/tasks/abc173_b" }
abc173-c = { alias = "c", problem = "https://atcoder.jp/contests/abc173/tasks/abc173_c" }
abc173-d = { alias = "d", problem = "https://atcoder.jp/contests/abc173/tasks/abc173_d" }
abc173-e = { alias = "e", problem = "https://atcoder.jp/contests/abc173/tasks/abc173_e" }
abc173-f = { alias = "f", problem = "https://atcoder.jp/contests/abc173/tasks/abc173_f" }

[[bin]]
name = "abc173-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc173-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc173-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc173-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc173-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc173-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
