[package]
name = "abc245"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc245-a", problem = "https://atcoder.jp/contests/abc245/<FIXME: screen name of the problem>"}
b = { name = "abc245-b", problem = "https://atcoder.jp/contests/abc245/<FIXME: screen name of the problem>"}
c = { name = "abc245-c", problem = "https://atcoder.jp/contests/abc245/<FIXME: screen name of the problem>"}
d = { name = "abc245-d", problem = "https://atcoder.jp/contests/abc245/<FIXME: screen name of the problem>"}
e = { name = "abc245-e", problem = "https://atcoder.jp/contests/abc245/<FIXME: screen name of the problem>"}
ex = { name = "abc245-ex", problem = "https://atcoder.jp/contests/abc245/<FIXME: screen name of the problem>"}
f = { name = "abc245-f", problem = "https://atcoder.jp/contests/abc245/<FIXME: screen name of the problem>"}
g = { name = "abc245-g", problem = "https://atcoder.jp/contests/abc245/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "abc245-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc245-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc245-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc245-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc245-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc245-ex"
path = "./src/bin/ex.rs"

[[bin]]
name = "abc245-f"
path = "./src/bin/f.rs"

[[bin]]
name = "abc245-g"
path = "./src/bin/g.rs"
