[package]
name = "abc154"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc154-a = { alias = "a", problem = "https://atcoder.jp/contests/abc154/tasks/abc154_a" }
abc154-b = { alias = "b", problem = "https://atcoder.jp/contests/abc154/tasks/abc154_b" }
abc154-c = { alias = "c", problem = "https://atcoder.jp/contests/abc154/tasks/abc154_c" }
abc154-d = { alias = "d", problem = "https://atcoder.jp/contests/abc154/tasks/abc154_d" }
abc154-e = { alias = "e", problem = "https://atcoder.jp/contests/abc154/tasks/abc154_e" }
abc154-f = { alias = "f", problem = "https://atcoder.jp/contests/abc154/tasks/abc154_f" }

[[bin]]
name = "abc154-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc154-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc154-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc154-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc154-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc154-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
