[package]
name = "abc361"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc361-a = { alias = "a", problem = "https://atcoder.jp/contests/abc361/tasks/abc361_a" }
abc361-b = { alias = "b", problem = "https://atcoder.jp/contests/abc361/tasks/abc361_b" }
abc361-c = { alias = "c", problem = "https://atcoder.jp/contests/abc361/tasks/abc361_c" }
abc361-d = { alias = "d", problem = "https://atcoder.jp/contests/abc361/tasks/abc361_d" }
abc361-e = { alias = "e", problem = "https://atcoder.jp/contests/abc361/tasks/abc361_e" }
abc361-f = { alias = "f", problem = "https://atcoder.jp/contests/abc361/tasks/abc361_f" }
abc361-g = { alias = "g", problem = "https://atcoder.jp/contests/abc361/tasks/abc361_g" }

[[bin]]
name = "abc361-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc361-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc361-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc361-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc361-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc361-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc361-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
