[package]
name = "abc418"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc418-a = { alias = "a", problem = "https://atcoder.jp/contests/abc418/tasks/abc418_a" }
abc418-b = { alias = "b", problem = "https://atcoder.jp/contests/abc418/tasks/abc418_b" }
abc418-c = { alias = "c", problem = "https://atcoder.jp/contests/abc418/tasks/abc418_c" }
abc418-d = { alias = "d", problem = "https://atcoder.jp/contests/abc418/tasks/abc418_d" }
abc418-e = { alias = "e", problem = "https://atcoder.jp/contests/abc418/tasks/abc418_e" }
abc418-f = { alias = "f", problem = "https://atcoder.jp/contests/abc418/tasks/abc418_f" }
abc418-g = { alias = "g", problem = "https://atcoder.jp/contests/abc418/tasks/abc418_g" }

[[bin]]
name = "abc418-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc418-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc418-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc418-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc418-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc418-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc418-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
