[package]
name = "arc143"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "arc143-a", problem = "https://atcoder.jp/contests/arc143/<FIXME: screen name of the problem>"}
"a 2" = { name = "arc143-a 2", problem = "https://atcoder.jp/contests/arc143/<FIXME: screen name of the problem>"}
b = { name = "arc143-b", problem = "https://atcoder.jp/contests/arc143/<FIXME: screen name of the problem>"}
c = { name = "arc143-c", problem = "https://atcoder.jp/contests/arc143/<FIXME: screen name of the problem>"}
d = { name = "arc143-d", problem = "https://atcoder.jp/contests/arc143/<FIXME: screen name of the problem>"}
e = { name = "arc143-e", problem = "https://atcoder.jp/contests/arc143/<FIXME: screen name of the problem>"}
f = { name = "arc143-f", problem = "https://atcoder.jp/contests/arc143/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "arc143-a"
path = "./src/bin/a.rs"

[[bin]]
name = "arc143-a 2"
path = "./src/bin/a 2.rs"

[[bin]]
name = "arc143-b"
path = "./src/bin/b.rs"

[[bin]]
name = "arc143-c"
path = "./src/bin/c.rs"

[[bin]]
name = "arc143-d"
path = "./src/bin/d.rs"

[[bin]]
name = "arc143-e"
path = "./src/bin/e.rs"

[[bin]]
name = "arc143-f"
path = "./src/bin/f.rs"
