[package]
name = "abc193"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc193-a = { alias = "a", problem = "https://atcoder.jp/contests/abc193/tasks/abc193_a" }
abc193-b = { alias = "b", problem = "https://atcoder.jp/contests/abc193/tasks/abc193_b" }
abc193-c = { alias = "c", problem = "https://atcoder.jp/contests/abc193/tasks/abc193_c" }
abc193-d = { alias = "d", problem = "https://atcoder.jp/contests/abc193/tasks/abc193_d" }
abc193-e = { alias = "e", problem = "https://atcoder.jp/contests/abc193/tasks/abc193_e" }
abc193-f = { alias = "f", problem = "https://atcoder.jp/contests/abc193/tasks/abc193_f" }

[[bin]]
name = "abc193-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc193-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc193-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc193-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc193-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc193-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
