[package]
edition = "2018"
name    = "abc146"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc146-a = { alias = "a", problem = "https://atcoder.jp/contests/abc146/tasks/abc146_a" }
abc146-b = { alias = "b", problem = "https://atcoder.jp/contests/abc146/tasks/abc146_b" }
abc146-c = { alias = "c", problem = "https://atcoder.jp/contests/abc146/tasks/abc146_c" }
abc146-d = { alias = "d", problem = "https://atcoder.jp/contests/abc146/tasks/abc146_d" }
abc146-e = { alias = "e", problem = "https://atcoder.jp/contests/abc146/tasks/abc146_e" }
abc146-f = { alias = "f", problem = "https://atcoder.jp/contests/abc146/tasks/abc146_f" }

[[bin]]
name = "abc146-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc146-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc146-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc146-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc146-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc146-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
