[package]
edition = "2018"
name    = "arc170"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
arc170-a = { alias = "a", problem = "https://atcoder.jp/contests/arc170/tasks/arc170_a" }
arc170-b = { alias = "b", problem = "https://atcoder.jp/contests/arc170/tasks/arc170_b" }
arc170-c = { alias = "c", problem = "https://atcoder.jp/contests/arc170/tasks/arc170_c" }
arc170-d = { alias = "d", problem = "https://atcoder.jp/contests/arc170/tasks/arc170_d" }
arc170-e = { alias = "e", problem = "https://atcoder.jp/contests/arc170/tasks/arc170_e" }
arc170-f = { alias = "f", problem = "https://atcoder.jp/contests/arc170/tasks/arc170_f" }

[[bin]]
name = "arc170-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc170-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc170-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc170-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc170-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc170-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
