[package]
name = "abc359"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc359-a = { alias = "a", problem = "https://atcoder.jp/contests/abc359/tasks/abc359_a" }
abc359-b = { alias = "b", problem = "https://atcoder.jp/contests/abc359/tasks/abc359_b" }
abc359-c = { alias = "c", problem = "https://atcoder.jp/contests/abc359/tasks/abc359_c" }
abc359-d = { alias = "d", problem = "https://atcoder.jp/contests/abc359/tasks/abc359_d" }
abc359-e = { alias = "e", problem = "https://atcoder.jp/contests/abc359/tasks/abc359_e" }
abc359-f = { alias = "f", problem = "https://atcoder.jp/contests/abc359/tasks/abc359_f" }
abc359-g = { alias = "g", problem = "https://atcoder.jp/contests/abc359/tasks/abc359_g" }

[[bin]]
name = "abc359-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc359-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc359-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc359-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc359-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc359-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc359-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
