[package]
name = "abc301"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc301-a", problem = "https://atcoder.jp/contests/abc301/<FIXME: screen name of the problem>"}
b = { name = "abc301-b", problem = "https://atcoder.jp/contests/abc301/<FIXME: screen name of the problem>"}
c = { name = "abc301-c", problem = "https://atcoder.jp/contests/abc301/<FIXME: screen name of the problem>"}
d = { name = "abc301-d", problem = "https://atcoder.jp/contests/abc301/<FIXME: screen name of the problem>"}
e = { name = "abc301-e", problem = "https://atcoder.jp/contests/abc301/<FIXME: screen name of the problem>"}
ex = { name = "abc301-ex", problem = "https://atcoder.jp/contests/abc301/<FIXME: screen name of the problem>"}
f = { name = "abc301-f", problem = "https://atcoder.jp/contests/abc301/<FIXME: screen name of the problem>"}
g = { name = "abc301-g", problem = "https://atcoder.jp/contests/abc301/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
proconio = "*"
itertools = "=0.9.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "abc301-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc301-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc301-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc301-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc301-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc301-ex"
path = "./src/bin/ex.rs"

[[bin]]
name = "abc301-f"
path = "./src/bin/f.rs"

[[bin]]
name = "abc301-g"
path = "./src/bin/g.rs"
