[package]
edition = "2018"
name    = "abc194"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc194-a = { alias = "a", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_a" }
abc194-b = { alias = "b", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_b" }
abc194-c = { alias = "c", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_c" }
abc194-d = { alias = "d", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_d" }
abc194-e = { alias = "e", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_e" }
abc194-f = { alias = "f", problem = "https://atcoder.jp/contests/abc194/tasks/abc194_f" }

[[bin]]
name = "abc194-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc194-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc194-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc194-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc194-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc194-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
