[package]
edition = "2018"
name    = "abc329"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc329-a = { alias = "a", problem = "https://atcoder.jp/contests/abc329/tasks/abc329_a" }
abc329-b = { alias = "b", problem = "https://atcoder.jp/contests/abc329/tasks/abc329_b" }
abc329-c = { alias = "c", problem = "https://atcoder.jp/contests/abc329/tasks/abc329_c" }
abc329-d = { alias = "d", problem = "https://atcoder.jp/contests/abc329/tasks/abc329_d" }
abc329-e = { alias = "e", problem = "https://atcoder.jp/contests/abc329/tasks/abc329_e" }
abc329-f = { alias = "f", problem = "https://atcoder.jp/contests/abc329/tasks/abc329_f" }
abc329-g = { alias = "g", problem = "https://atcoder.jp/contests/abc329/tasks/abc329_g" }

[[bin]]
name = "abc329-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc329-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc329-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc329-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc329-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc329-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc329-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
