[package]
edition = "2018"
name    = "abc409"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc409-a = { alias = "a", problem = "https://atcoder.jp/contests/abc409/tasks/abc409_a" }
abc409-b = { alias = "b", problem = "https://atcoder.jp/contests/abc409/tasks/abc409_b" }
abc409-c = { alias = "c", problem = "https://atcoder.jp/contests/abc409/tasks/abc409_c" }
abc409-d = { alias = "d", problem = "https://atcoder.jp/contests/abc409/tasks/abc409_d" }
abc409-e = { alias = "e", problem = "https://atcoder.jp/contests/abc409/tasks/abc409_e" }
abc409-f = { alias = "f", problem = "https://atcoder.jp/contests/abc409/tasks/abc409_f" }
abc409-g = { alias = "g", problem = "https://atcoder.jp/contests/abc409/tasks/abc409_g" }

[[bin]]
name = "abc409-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc409-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc409-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc409-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc409-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc409-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc409-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
