[package]
edition = "2021"
name    = "abc274"
version = "0.1.0"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a  = { name = "abc274-a", problem = "https://atcoder.jp/contests/abc274/<FIXME: screen name of the problem>" }
b  = { name = "abc274-b", problem = "https://atcoder.jp/contests/abc274/<FIXME: screen name of the problem>" }
c  = { name = "abc274-c", problem = "https://atcoder.jp/contests/abc274/<FIXME: screen name of the problem>" }
d  = { name = "abc274-d", problem = "https://atcoder.jp/contests/abc274/<FIXME: screen name of the problem>" }
e  = { name = "abc274-e", problem = "https://atcoder.jp/contests/abc274/<FIXME: screen name of the problem>" }
ex = { name = "abc274-ex", problem = "https://atcoder.jp/contests/abc274/<FIXME: screen name of the problem>" }
f  = { name = "abc274-f", problem = "https://atcoder.jp/contests/abc274/<FIXME: screen name of the problem>" }
g  = { name = "abc274-g", problem = "https://atcoder.jp/contests/abc274/<FIXME: screen name of the problem>" }

# dependencies added to new project
[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[profile.release]
lto   = true
panic = 'abort'

[[bin]]
name = "abc274-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc274-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc274-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc274-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc274-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc274-ex"
path = "./src/bin/ex.rs"

[[bin]]
name = "abc274-f"
path = "./src/bin/f.rs"

[[bin]]
name = "abc274-g"
path = "./src/bin/g.rs"
