[package]
name = "abc410"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc410-a = { alias = "a", problem = "https://atcoder.jp/contests/abc410/tasks/abc410_a" }
abc410-b = { alias = "b", problem = "https://atcoder.jp/contests/abc410/tasks/abc410_b" }
abc410-c = { alias = "c", problem = "https://atcoder.jp/contests/abc410/tasks/abc410_c" }
abc410-d = { alias = "d", problem = "https://atcoder.jp/contests/abc410/tasks/abc410_d" }
abc410-e = { alias = "e", problem = "https://atcoder.jp/contests/abc410/tasks/abc410_e" }
abc410-f = { alias = "f", problem = "https://atcoder.jp/contests/abc410/tasks/abc410_f" }
abc410-g = { alias = "g", problem = "https://atcoder.jp/contests/abc410/tasks/abc410_g" }

[[bin]]
name = "abc410-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc410-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc410-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc410-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc410-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc410-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc410-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
