[package]
edition = "2018"
name    = "abc413"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
abc413-a = { alias = "a", problem = "https://atcoder.jp/contests/abc413/tasks/abc413_a" }
abc413-b = { alias = "b", problem = "https://atcoder.jp/contests/abc413/tasks/abc413_b" }
abc413-c = { alias = "c", problem = "https://atcoder.jp/contests/abc413/tasks/abc413_c" }
abc413-d = { alias = "d", problem = "https://atcoder.jp/contests/abc413/tasks/abc413_d" }
abc413-e = { alias = "e", problem = "https://atcoder.jp/contests/abc413/tasks/abc413_e" }
abc413-f = { alias = "f", problem = "https://atcoder.jp/contests/abc413/tasks/abc413_f" }
abc413-g = { alias = "g", problem = "https://atcoder.jp/contests/abc413/tasks/abc413_g" }

[[bin]]
name = "abc413-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc413-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc413-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc413-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc413-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc413-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc413-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
