[package]
edition = "2018"
name    = "arc119"
version = "0.1.0"

[package.metadata.cargo-compete.bin]
arc119-a = { alias = "a", problem = "https://atcoder.jp/contests/arc119/tasks/arc119_a" }
arc119-b = { alias = "b", problem = "https://atcoder.jp/contests/arc119/tasks/arc119_b" }
arc119-c = { alias = "c", problem = "https://atcoder.jp/contests/arc119/tasks/arc119_c" }
arc119-d = { alias = "d", problem = "https://atcoder.jp/contests/arc119/tasks/arc119_d" }
arc119-e = { alias = "e", problem = "https://atcoder.jp/contests/arc119/tasks/arc119_e" }
arc119-f = { alias = "f", problem = "https://atcoder.jp/contests/arc119/tasks/arc119_f" }

[[bin]]
name = "arc119-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc119-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc119-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc119-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc119-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc119-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[dev-dependencies]
