[package]
name = "agc060"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
agc060-a = { alias = "a", problem = "https://atcoder.jp/contests/agc060/tasks/agc060_a" }
agc060-b = { alias = "b", problem = "https://atcoder.jp/contests/agc060/tasks/agc060_b" }
agc060-c = { alias = "c", problem = "https://atcoder.jp/contests/agc060/tasks/agc060_c" }
agc060-d = { alias = "d", problem = "https://atcoder.jp/contests/agc060/tasks/agc060_d" }
agc060-e = { alias = "e", problem = "https://atcoder.jp/contests/agc060/tasks/agc060_e" }
agc060-f = { alias = "f", problem = "https://atcoder.jp/contests/agc060/tasks/agc060_f" }

[[bin]]
name = "agc060-a"
path = "src/bin/a.rs"

[[bin]]
name = "agc060-b"
path = "src/bin/b.rs"

[[bin]]
name = "agc060-c"
path = "src/bin/c.rs"

[[bin]]
name = "agc060-d"
path = "src/bin/d.rs"

[[bin]]
name = "agc060-e"
path = "src/bin/e.rs"

[[bin]]
name = "agc060-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
