[package]
name = "abc189"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc189-a = { alias = "a", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_a" }
abc189-b = { alias = "b", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_b" }
abc189-c = { alias = "c", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_c" }
abc189-d = { alias = "d", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_d" }
abc189-e = { alias = "e", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_e" }
abc189-f = { alias = "f", problem = "https://atcoder.jp/contests/abc189/tasks/abc189_f" }

[[bin]]
name = "abc189-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc189-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc189-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc189-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc189-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc189-f"
path = "src/bin/f.rs"

[dependencies]
proconio="=0.4.5"
itertools="=0.11.0"

[dev-dependencies]
