[package]
name = "abc406"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
abc406-a = { alias = "a", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_a" }
abc406-b = { alias = "b", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_b" }
abc406-c = { alias = "c", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_c" }
abc406-d = { alias = "d", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_d" }
abc406-e = { alias = "e", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_e" }
abc406-f = { alias = "f", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_f" }
abc406-g = { alias = "g", problem = "https://atcoder.jp/contests/abc406/tasks/abc406_g" }

[[bin]]
name = "abc406-a"
path = "src/bin/a.rs"

[[bin]]
name = "abc406-b"
path = "src/bin/b.rs"

[[bin]]
name = "abc406-c"
path = "src/bin/c.rs"

[[bin]]
name = "abc406-d"
path = "src/bin/d.rs"

[[bin]]
name = "abc406-e"
path = "src/bin/e.rs"

[[bin]]
name = "abc406-f"
path = "src/bin/f.rs"

[[bin]]
name = "abc406-g"
path = "src/bin/g.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
