[package]
edition = "2021"
name    = "abc223"
version = "0.1.0"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "abc223-a", problem = "https://atcoder.jp/contests/abc223/<FIXME: screen name of the problem>" }
b = { name = "abc223-b", problem = "https://atcoder.jp/contests/abc223/<FIXME: screen name of the problem>" }
c = { name = "abc223-c", problem = "https://atcoder.jp/contests/abc223/<FIXME: screen name of the problem>" }
d = { name = "abc223-d", problem = "https://atcoder.jp/contests/abc223/<FIXME: screen name of the problem>" }
e = { name = "abc223-e", problem = "https://atcoder.jp/contests/abc223/<FIXME: screen name of the problem>" }
f = { name = "abc223-f", problem = "https://atcoder.jp/contests/abc223/<FIXME: screen name of the problem>" }
g = { name = "abc223-g", problem = "https://atcoder.jp/contests/abc223/<FIXME: screen name of the problem>" }
h = { name = "abc223-h", problem = "https://atcoder.jp/contests/abc223/<FIXME: screen name of the problem>" }

# dependencies added to new project
[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[profile.release]
lto   = true
panic = 'abort'

[[bin]]
name = "abc223-a"
path = "./src/bin/a.rs"

[[bin]]
name = "abc223-b"
path = "./src/bin/b.rs"

[[bin]]
name = "abc223-c"
path = "./src/bin/c.rs"

[[bin]]
name = "abc223-d"
path = "./src/bin/d.rs"

[[bin]]
name = "abc223-e"
path = "./src/bin/e.rs"

[[bin]]
name = "abc223-f"
path = "./src/bin/f.rs"

[[bin]]
name = "abc223-g"
path = "./src/bin/g.rs"

[[bin]]
name = "abc223-h"
path = "./src/bin/h.rs"
