[package]
edition = "2021"
name    = "ddcc2020-qual"
version = "0.1.0"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "ddcc2020-qual-a", problem = "https://atcoder.jp/contests/ddcc2020-qual/<FIXME: screen name of the problem>" }
b = { name = "ddcc2020-qual-b", problem = "https://atcoder.jp/contests/ddcc2020-qual/<FIXME: screen name of the problem>" }
c = { name = "ddcc2020-qual-c", problem = "https://atcoder.jp/contests/ddcc2020-qual/<FIXME: screen name of the problem>" }
d = { name = "ddcc2020-qual-d", problem = "https://atcoder.jp/contests/ddcc2020-qual/<FIXME: screen name of the problem>" }
e = { name = "ddcc2020-qual-e", problem = "https://atcoder.jp/contests/ddcc2020-qual/<FIXME: screen name of the problem>" }
f = { name = "ddcc2020-qual-f", problem = "https://atcoder.jp/contests/ddcc2020-qual/<FIXME: screen name of the problem>" }

# dependencies added to new project
[dependencies]
ac-library-rs = "0.1.1"
itertools     = "=0.11.0"
proconio      = "=0.4.5"

[profile.release]
lto   = true
panic = 'abort'

[[bin]]
name = "ddcc2020-qual-a"
path = "./src/bin/a.rs"

[[bin]]
name = "ddcc2020-qual-b"
path = "./src/bin/b.rs"

[[bin]]
name = "ddcc2020-qual-c"
path = "./src/bin/c.rs"

[[bin]]
name = "ddcc2020-qual-d"
path = "./src/bin/d.rs"

[[bin]]
name = "ddcc2020-qual-e"
path = "./src/bin/e.rs"

[[bin]]
name = "ddcc2020-qual-f"
path = "./src/bin/f.rs"
