[package]
name = "arc172"
version = "0.1.0"
edition = "2018"

[package.metadata.cargo-compete.bin]
arc172-a = { alias = "a", problem = "https://atcoder.jp/contests/arc172/tasks/arc172_a" }
arc172-b = { alias = "b", problem = "https://atcoder.jp/contests/arc172/tasks/arc172_b" }
arc172-c = { alias = "c", problem = "https://atcoder.jp/contests/arc172/tasks/arc172_c" }
arc172-d = { alias = "d", problem = "https://atcoder.jp/contests/arc172/tasks/arc172_d" }
arc172-e = { alias = "e", problem = "https://atcoder.jp/contests/arc172/tasks/arc172_e" }
arc172-f = { alias = "f", problem = "https://atcoder.jp/contests/arc172/tasks/arc172_f" }

[[bin]]
name = "arc172-a"
path = "src/bin/a.rs"

[[bin]]
name = "arc172-b"
path = "src/bin/b.rs"

[[bin]]
name = "arc172-c"
path = "src/bin/c.rs"

[[bin]]
name = "arc172-d"
path = "src/bin/d.rs"

[[bin]]
name = "arc172-e"
path = "src/bin/e.rs"

[[bin]]
name = "arc172-f"
path = "src/bin/f.rs"

[dependencies]
ac-library-rs="0.1.1"
itertools="=0.11.0"
proconio="=0.4.5"

[dev-dependencies]
