[package]
name = "mujin-pc-2016"
version = "0.1.0"
edition = "2021"

[package.metadata.cargo-compete]
config = "../compete.toml"

[package.metadata.cargo-compete.bin]
a = { name = "mujin-pc-2016-a", problem = "https://atcoder.jp/contests/mujin-pc-2016/<FIXME: screen name of the problem>"}
b = { name = "mujin-pc-2016-b", problem = "https://atcoder.jp/contests/mujin-pc-2016/<FIXME: screen name of the problem>"}
c = { name = "mujin-pc-2016-c", problem = "https://atcoder.jp/contests/mujin-pc-2016/<FIXME: screen name of the problem>"}
d = { name = "mujin-pc-2016-d", problem = "https://atcoder.jp/contests/mujin-pc-2016/<FIXME: screen name of the problem>"}
e = { name = "mujin-pc-2016-e", problem = "https://atcoder.jp/contests/mujin-pc-2016/<FIXME: screen name of the problem>"}

# dependencies added to new project
[dependencies]
ac-library-rs="0.1.1"
proconio="=0.4.5"
itertools="=0.11.0"

[profile.release]
lto = true
panic = 'abort'

[[bin]]
name = "mujin-pc-2016-a"
path = "./src/bin/a.rs"

[[bin]]
name = "mujin-pc-2016-b"
path = "./src/bin/b.rs"

[[bin]]
name = "mujin-pc-2016-c"
path = "./src/bin/c.rs"

[[bin]]
name = "mujin-pc-2016-d"
path = "./src/bin/d.rs"

[[bin]]
name = "mujin-pc-2016-e"
path = "./src/bin/e.rs"
